version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: liquid
      MONGO_INITDB_ROOT_PASSWORD: 220051
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: liquid
      ME_CONFIG_MONGODB_ADMINPASSWORD: 220051
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mongo-network

  app:
    image: liquid003/test:1.0   # Change to your Docker Hub image
    container_name: test-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://liquid:220051@mongo:27017/?authSource=admin
    networks:
      - mongo-network

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge